site_name: Maximo Application Suite (MAS) Performance Wiki
site_url: https://ibm-mas.github.io/mas-performance

repo_name: GitHub
repo_url: https://github.com/ibm-mas/mas-performance
edit_uri: blob/master/docs/

nav:
  - 'Home': index.md
  - 'MAS':
    - 'Best Practice':
      - 'OpenShift Container Platform': mas/ocp/bestpractice.md
      - 'MAS Core': mas/core/bestpractice.md
      - 'MAS IoT': mas/iot/bestpractice.md
      - 'MAS Manage': 
        - 'Overview': mas/manage/bestpractice.md
        - 'Mobile': mas/mobile/bestpractice.md
        - 'Integration Framework (MIF)':
          - 'JMS': mas/mif-jms/bestpractice.md
          - 'Kafka': mas/mif-kafka/bestpractice.md
        - 'Industry Solutions':
          - 'Manage IT': mas/manage-it/bestpractice.md 
          - 'Oil and Gas/HSE': mas/manage-industry-solutions/ong-hse/bestpractice.md
          - 'Transportation': mas/manage-industry-solutions/transportation/bestpractice.md
        - 'Work Order Intelligence (AI)':
          - 'Training': mas/manage/woi-train.md
          - 'Inferencing': mas/manage/woi-infer.md
        - "Scripting Best Practice": https://ibm-maximo-dev.github.io/maximo-autoscript-documentation/bestpractice/overview
      - 'MAS Visual Inspection': mas/mvi/bestpractice.md
      - 'AWS': mas/aws/bestpractice.md
      - 'IBM Cloud': mas/ibmcloud/bestpractice.md
      - 'Azure': mas/azure/bestpractice.md
      - 'MongoDB': mas/mongodb/bestpractice.md
    - 'Sizing Guidance': mas/sizing/guidance.md
    - 'Monitoring': mas/monitoring/guidance.md
  - 'Maximo 7.x':
    - 'Best Practice': maximo-7/bestpractice.md
  - 'Performance Diagnosis':
    - 'Performance Test Best Practice': pd/ptbp.md
    - 'Diagnosis Check List': pd/checklist.md
    - 'DB2 Performance Diagnosis': pd/db2-performance-diagnosis.md
    - 'DBTest Utility':
      - 'MAS Manage': pd/dbtest.md
      - 'Maximo 7.6': pd/dbtest-76.md
    - 'PingTest Utility': pd/pingtest.md
    - 'IBM Maximo Cluster Performance Insights': https://ibm-mas.github.io/mcpi/ #pd/mcpi/maximo-cpi.md
    - 'JVM Performance Insight': pd/jvm-performance-insight.md
  - 'Reference':
    - 'Upgrade IBM Maximo to MAS on VMware vSphere - Lessons Learned': https://github.com/zxue/upgrade-ibm-maximo-to-mas-on-vsphere


theme:
  name: readthedocs
  language: en
  highlightjs: true
  hljs_languages:
    - yaml
  prev_next_buttons_location: none
  feature:
    - navigation.instant

extra_css:
  - extra.css

markdown_extensions:
  - toc:
      permalink: ÔÉÅ
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
